apps/cms/urls.py
from django.urls import path
from . import views

app_name = 'cms'

urlpatterns = [
    path('',views.index,name='index'),
    path('write_news/',views.WriteNewsView.as_view(),name='write_news'),
    path('news_category/',views.news_category,name='news_category'),
    path('add_news_category/',views.add_news_category,name='add_news_category'),
    path('edit_news_category/',views.edit_news_category,name='edit_news_category'),
    path('delete_news_category/',views.delete_news_category,name='delete_news_category'),
    path('upload_file/',views.upload_file,name='upload_file'),
]

apps/pua_auth/urls.py
from django.urls import path
from . import views

app_name = "pua_auth"

urlpatterns = [
    path('login/',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout'),
    path('img_captcha/',views.img_captcha,name='img_captcha'),
    path('register/',views.register,name='register'),
]

one/urls.py
from django.urls import path,include
from apps.news import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('news/', include("apps.news.urls")),
    path('cms/',include("apps.cms.urls")),
    path('account/',include("apps.pua_auth.urls")),
    path('',views.index,name='index'),
    path('baike/',include("apps.baike.urls")),
    path('ueditor/',include("apps.ueditor.urls")),
    path('puaheart/', include('apps.puaheart.urls')),
    path('we/', include('apps.we.urls')),

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

apps/cms/models.py
from django.db import models

# Create your models here.

apps/cms/forms.py
#encoding: utf-8

from apps.forms import FormMixin
from django import forms
from apps.news.models import News

class EditNewsCategoryForm(forms.Form):
    pk = forms.IntegerField(error_messages={"required":"必须传入分类的id！"})
    name = forms.CharField(max_length=100)


class WriteNewsForm(forms.ModelForm,FormMixin):
    category = forms.IntegerField()
    class Meta:
        model = News
        exclude = ['category','author','pub_time']

apps/cms/views.py
from django.shortcuts import render
from django.contrib.admin.views.decorators import staff_member_required
from django.views.generic import View
from django.views.decorators.http import require_POST,require_GET
from apps.news.models import NewsCategory,News
from utils import restful
from .forms import EditNewsCategoryForm,WriteNewsForm
import os
from django.conf import settings

@staff_member_required(login_url='index')
def index(request):
    return render(request,'cms/index.html')

class WriteNewsView(View):
    def get(self,request):
        categories = NewsCategory.objects.all()
        context = {
            'categories': categories
        }
        return render(request,'cms/write_news.html',context=context)

    def post(self,request):
        form = WriteNewsForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            desc = form.cleaned_data.get('desc')
            thumbnail = form.cleaned_data.get('thumbnail')
            content = form.cleaned_data.get('content')
            category_id = form.cleaned_data.get('category')
            category = NewsCategory.objects.get(pk=category_id)
            News.objects.create(title=title,desc=desc,thumbnail=thumbnail,content=content,category=category,author=request.user)
            return restful.ok()
        else:
            return restful.params_error(message=form.get_errors())



@require_GET
def news_category(request):
    categories = NewsCategory.objects.all()
    context = {
        'categories':categories
    }
    return render(request, 'cms/news_category.html',context=context)

@require_POST
def add_news_category(request):
    name = request.POST.get('name')
    exists = NewsCategory.objects.filter(name=name).exists()
    if not exists:
        NewsCategory.objects.create(name=name)
        return restful.ok()
    else:
        return restful.params_error(message='该分类已经存在！')


@require_POST
def edit_news_category(request):
    form = EditNewsCategoryForm(request.POST)
    if form.is_valid():
        pk = form.cleaned_data.get('pk')
        name = form.cleaned_data.get('name')
        try:
            NewsCategory.objects.filter(pk=pk).update(name=name)
            return restful.ok()
        except:
            return restful.params_error(message='该分类不存在！')
    else:
        return restful.params_error(message=form.get_error())


@require_POST
def delete_news_category(request):
    pk = request.POST.get('pk')
    try:
        NewsCategory.objects.filter(pk=pk).delete()
        return restful.ok()
    except:
        return restful.unauth(message='该分类不存在！')


@require_POST
def upload_file(request):
    file = request.FILES.get('file')
    name = file.name
    with open(os.path.join(settings.MEDIA_ROOT,name),'wb') as fp:
        for chunk in file.chunks():
            fp.write(chunk)
    url = request.build_absolute_uri(settings.MEDIA_URL+name)
    # http://127.0.1:8000/media/abc.jpg
    return restful.result(data={'url':url})

front/templates/cms/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %} | PUA管理系统</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/dist/css/AdminLTE.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/dist/css/skins/_all-skins.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/morris.js/morris.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css' %}">
    <link rel="stylesheet" href="{% static 'sweetalert/sweetalert.css' %}">
    <script src="{% static 'adminlte/bower_components/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'adminlte/bower_components/jquery-ui/jquery-ui.min.js' %}"></script>
    <script src="{% static 'adminlte/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'adminlte/dist/js/adminlte.min.js' %}"></script>
    <script src="{% static 'adminlte/dist/js/demo.js' %}"></script>
    <script src="{% static 'sweetalert/sweetalert.min.js' %}"></script>
    <script src="{% static 'js/puaajax.min.js' %}"></script>
    <script src="{% static 'js/alert.min.js' %}"></script>
    <script src="{% static 'js/message.min.js' %}"></script>
        {% block head %}{% endblock %}
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
    <header class="main-header">
    <a href="index2.html" class="logo">
      <span class="logo-mini"><b>CMS</b></span>
      <span class="logo-lg">PUA后台管理系统</span>
    </a>
    <nav class="navbar navbar-static-top">
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <img src="https://ps.ssl.qhimg.com/t01f018e1efc55a0e62.jpg" class="user-image" alt="User Image">
              <span class="hidden-xs">秦琪</span>
            </a>
            <ul class="dropdown-menu">

              <li class="user-header">
                <img src="https://ps.ssl.qhimg.com/t01f018e1efc55a0e62.jpg" class="img-circle" alt="User Image">
                <p>
                  秦琪
                  <small>系统管理员</small>
                </p>
              </li>
              <li class="user-footer">
                <div class="pull-left">
                  <a href="#" class="btn btn-default btn-flat">个人中心</a>
                </div>
                <div class="pull-right">
                  <a href="#" class="btn btn-default btn-flat">退出登录</a>
                </div>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>
  </header>
    <aside class="main-sidebar">
    <section class="sidebar">
      <form action="#" method="get" class="sidebar-form">
        <div class="input-group">
          <input type="text" name="q" class="form-control" placeholder="首页">
          <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
        </div>
      </form>
      <ul class="sidebar-menu" data-widget="tree">
        <li class="active">
            <a href="{% url 'cms:index' %}">
                <i class="fa fa-home"></i>
                <span>首页</span>
            </a>
        </li>
          <li class="header">新闻管理</li>
          <li>
              <a href="{% url 'cms:write_news' %}">
                  <i class="fa fa-edit"></i>
                  <span>发布新闻</span>
              </a>
          </li>
          <li>
              <a href="{% url 'cms:news_category' %}">
                  <i class="fa fa-tag"></i>
                  <span>新闻分类</span>
              </a>
          </li>
      </ul>
    </section>
  </aside>
    <div class="content-wrapper">
      <section class="content-header">
            {% block content-header %}{% endblock %}
      </section>
      <section class="content">
            {% block content %}

            {% endblock %}
      </section>
  </div>
    <footer class="main-footer">
        <strong>PUA</strong>后台管理系统
  </footer>
</div>
</body>
</html>

front/templates/cms/index.html
{% extends 'cms/base.html' %}

{% block title %}首页{% endblock %}

{% block content-header %}
    <h1>欢迎来到PUA后台管理系统</h1>
{% endblock %}

front/templates/cms/login.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>CMS</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="{% static 'adminlte/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'adminlte/bower_components/font-awesome/css/font-awesome.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{% static 'adminlte/bower_components/Ionicons/css/ionicons.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'adminlte/dist/css/AdminLTE.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static 'adminlte/plugins/iCheck/square/blue.css' %}">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="#">PUA后台管理系统</a>
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">请登录</p>

    <form action="{% url 'pua_auth:login' %}" method="post">
        {% csrf_token %}
      <div class="form-group has-feedback">
        <input type="text" class="form-control" name="telephone" placeholder="手机号码">
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        <input type="password" class="form-control" name="password" placeholder="密码">
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>
      <div class="row">
        <div class="col-xs-8">
          <div class="checkbox icheck">
            <label>
              <input type="checkbox" name="remember"> 记住我
            </label>
          </div>
        </div>
        <!-- /.col -->
        <div class="col-xs-4">
          <button type="submit" class="btn btn-primary btn-block btn-flat">登录</button>
        </div>
        <!-- /.col -->
      </div>
    </form>
  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

<!-- jQuery 3 -->
<script src="{% static 'adminlte/bower_components/jquery/dist/jquery.min.js' %}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static 'adminlte/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<!-- iCheck -->
<script src="{% static 'adminlte/plugins/iCheck/icheck.min.js' %}"></script>
<script>
  $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' /* optional */
    });
  });
</script>
</body>
</html>

front/templates/cms/news_category.html
{% extends 'cms/base.html' %}

{% block title %}
新闻分类
{% endblock %}

{% block head %}
    <script src="{% static 'js/news_category.min.js' %}"></script>
{% endblock %}

{% block content-header %}
<h1>新闻分类</h1>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                    <button id="add-btn" class="btn btn-primary pull-right">添加分类</button>
                </div>
                <div class="box-body">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>分类名称</th>
                                <th>新闻数量</th>
                                <th>操作</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for category in categories %}
                                <tr data-pk="{{ category.pk }}" data-name="{{ category.name }}">
                                <td>{{ category.name }}</td>
                                <td>30</td>
                                <td>
                                    <button class="btn btn-warning btn-xs edit-btn">编辑</button>
                                    <button class="btn btn-danger btn-xs delete-btn">删除</button>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

front/templates/cms/write_news.html
{% extends 'cms/base.html' %}

{% block title %}发布新闻{% endblock %}

{% block head %}
    <script src="{% static 'js/write_news.min.js' %}"></script>
    <script src="{% static 'ueditor/ueditor.config.js' %}"></script>
    <script src="{% static 'ueditor/ueditor.all.min.js' %}"></script>
{% endblock %}

{% block content-header %}
    <h1>发布新闻</h1>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <form action="" class="form">
                    <div class="box-body">
                        <div class="form-group">
                            <label for="title-form">标题</label>
                            <input type="text" class="form-control" name="title" id="title-form">
                        </div>
                        <div class="form-group">
                            <label for="category-form">分类</label>
                            <select name="category" id="category-form" class="form-control">
                                {% for category in categories %}
                                    <option value="{{ category.pk }}">{{ category.name }}</option>
                                {% endfor %}

                            </select>
                        </div>
                        <div class="form-group">
                            <label for="desc-form">描述</label>
                            <input type="text" class="form-control" name="desc" id="desc-form">
                        </div>
                        <div class="form-group">
                            <label for="thumbnail-form">缩略图</label>
                            <div class="input-group">
                                <input type="text" class="form-control" name="thumbnail" id="thumbnail-form">
                                <span class="input-group-btn">
                                    <label class="btn btn-default btn-file">
                                        上传图片<input hidden type="file" class="btn btn-default" id="thumbnail-btn">
                                    </label>
                                </span>
                            </div>
                        </div>
                        <div id="progress-group" class="form-group" style="display: none;">
                            <div class="progress">
                                <div class="progress-bar progress-bar-info progress-bar-striped" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 0%">
                                    0%
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="content-form">内容</label>
                            <script id="editor" type="text/plain"></script>
                        </div>
                    </div>
                    <div class="box-footer">
                        <button id="submit-btn" class="btn btn-primary pull-right">发布新闻</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}