apps/baike/urls.py
from django.urls import path
from . import views

app_name = 'baike'

urlpatterns = [
    path('',views.baike_index,name='baike_index'),
]

apps/cms/urls.py
from django.urls import path
from . import views

app_name = 'cms'

urlpatterns = [
    path('',views.index,name='index'),
    path('write_news/',views.WriteNewsView.as_view(),name='write_news'),
    path('news_category/',views.news_category,name='news_category'),
    path('add_news_category/',views.add_news_category,name='add_news_category'),
    path('edit_news_category/',views.edit_news_category,name='edit_news_category'),
    path('delete_news_category/',views.delete_news_category,name='delete_news_category'),
    path('upload_file/',views.upload_file,name='upload_file'),
]

apps/pua_auth/urls.py
from django.urls import path
from . import views

app_name = "pua_auth"

urlpatterns = [
    path('login/',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout'),
    path('img_captcha/',views.img_captcha,name='img_captcha'),
    path('register/',views.register,name='register'),
]

apps/puaheart/urls.py
from django.urls import path
from .import views

app_name = 'puaheart'

urlpatterns = [
    path('', views.choose, name='choose'),
    path('one/', views.one, name='one'),
    path('two/', views.two, name='two')
]

apps/we/urls.py
from django.urls import path
from .import views

app_name = 'we'

urlpatterns = [
    path('', views.contract, name='contract'),

]

one/urls.py
from django.urls import path,include
from apps.news import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('news/', include("apps.news.urls")),
    path('cms/',include("apps.cms.urls")),
    path('account/',include("apps.pua_auth.urls")),
    path('',views.index,name='index'),
    path('baike/',include("apps.baike.urls")),
    path('ueditor/',include("apps.ueditor.urls")),
    path('puaheart/', include('apps.puaheart.urls')),
    path('we/', include('apps.we.urls')),

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

apps/we/views.py
from django.shortcuts import render

def contract(request):
    return render(request, 'common/we.html')

front/templates/common/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
    <link rel="stylesheet" href="{% static 'css/login.min.css' %}">
    <link rel="stylesheet" href="//at.alicdn.com/t/font_1322535_gkbpeprt9cu.css">
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/login.min.js' %}"></script>
</head>
<body>
    <div class="mask-wrapper">
        <div class="auth-wrapper">
            <div class="close-wrapper">
                <span class="close-btn icon-close iconfont"></span>
            </div>
            <div class="auth-inner-wrapper">
                <div class="scroll-wrapper">
                    <div class="signin-group auth-group">
                        <div class="top-group">
                            <span class="title">请登录</span>
                            <a href="javascript: void(0);" class="switch">立即注册></a>
                        </div>
                        <div class="form-group">
                            <div class="input-group">
                                <input type="text" class="form-control" name="telephone" placeholder="请输入手机号码">
                            </div>
                             <div class="input-group">
                                <input type="password" class="form-control" name="password" placeholder="请输入密码">
                            </div>
                            <div class="input-group">
                                <label class="remember-label">
                                    <input type="checkbox" name="remember" value="1">
                                    记住我
                                </label>
                            </div>
                            <div class="input-group">
                                <input type="submit" class="submit-btn" value="立即登录">
                            </div>
                        </div>
                    </div>
                    <div class="signup-group auth-group">
                        <div class="top-group">
                            <span class="title">请注册</span>
                            <a href="javascript: void(0);" class="switch">立即登录></a>
                        </div>
                        <div class="form-group">
                            <div class="input-group">
                                <input type="text" class="form-control" name="telephone" placeholder="手机号码">
                            </div>
                            <div class="input-group">
                                <input type="text" class="form-control" name="username" placeholder="用户名">
                            </div>
                            <div class="input-group">
                                <div class="short-input-group">
                                    <input type="text" class="form-control" name="img_captcha" placeholder="图形验证码">
                                </div>
                                <div class="input-group-addon">
                                    <img src="" alt="">
                                </div>
                            </div>
                            <div class="input-group">
                                <input type="text" class="form-control" name="password1" placeholder="密码">
                            </div>
                            <div class="input-group">
                                <input type="text" class="form-control" name="password2" placeholder="确认密码">
                            </div>
                            <div class="input-group">
                                <div class="short-input-group">
                                    <input type="text" class="form-control" name="sms_captcha" placeholder="短信验证码">
                                </div>
                                <div class="input-group-addon">
                                    <span class="sms-captcha-btn">发送验证码</span>
                                </div>
                            </div>
                            <div class="input-group">
                                <input type="submit" class="submit-btn" value="立即注册">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

front/templates/common/we.html
{% extends 'base/header.html' %}

{% block title %}
    关于我们
{% endblock %}

{% block head %}
     <link rel="stylesheet" href="{% static 'css/we.min.css' %}">
{% endblock %}

{#{% block header %}#}
{#    <header class="header">#}
{#        <div class="container">#}
{#            <div class="logo-box">#}
{#                <a href="index.html">#}
{#                    <img src="{% static 'images/logot.png' %}" alt="">#}
{#                </a>#}
{#            </div>#}
{##}
{#            <ul class="nav" type="none" style="{list-style-type: none}">#}
{#                <li class="active"><a href="/">首页</a></li>#}
{#                <li class="active"><a href="{% url 'baike:baike_index' %}">PUA百科</a></li>#}
{#                <li class="active"><a href="{% url 'puaheart:choose' %}">心理测试</a></li>#}
{#                <li class="active"><a href="http://m.66rpg.com/h5/1417969?ohp=v2&quality=32">角色扮演</a></li>#}
{#                <li class="active"><a href="{% url 'we:contract' %}">关于我们</a></li>#}
{#            </ul>#}
{##}
{#            <div class="auth-box">#}
{#                <i class="icon-personal_set iconfont"></i>#}
{#                {% if user.is_authenticated %}#}
{#                    <a href="#" class="authenticated-box">{{ user.username }}</a>#}
{#                    <div class="user-more-box">#}
{#                        <i class="triangle"></i>#}
{#                        {% if user.is_staff %}#}
{#                            <a href="{% url 'cms:index' %}">管理系统</a>#}
{#                        {% endif %}#}
{#                        <a href="{% url 'pua_auth:logout' %}">退出登录</a>#}
{#                    </div>#}
{#                {% else %}#}
{#                    <a href="#" class="signin-btn">登录</a> /#}
{#                    <a href="#" class="signup-btn">注册</a>#}
{#                {% endif %}#}
{#            </div>#}
{#        </div>#}
{#    </header>#}
{##}
{#{% endblock %}#}

{% block main %}
    <div class="one" style="height: 100px;">
    <div style="position: absolute; width: 608px; height: 148px; left: 327.5px; top: 300px; transform: rotate(0deg);"><div data-v-7a35ef72="" class="pc_text" style="padding-left: 4px; text-align: center;"><span><span id="" style="font-size: 16px; box-sizing: border-box; line-height: 1.9em; font-family: 微软雅黑; color: rgb(121, 121, 121); font-style: normal; font-weight: 400; text-decoration: none; text-shadow: none; letter-spacing: 0px; text-indent: 0.01px; background-color: rgba(0, 0, 0, 0);">这是一个帮助你了解不良PUA的好地方。你可以利用这个空间更详细地了解人类的感情世界。我曾经对爱情有过无数美好幻想，两人相互吸引，了解彼此，而后交付真心，共同经营。但现实告诉我，有时候所谓的恋爱，往往只是一场精心策划的游戏</span><span style="font-family: 微软雅黑; font-size: 16px; color: rgb(121, 121, 121); font-style: normal; font-weight: 400; text-decoration: none; text-shadow: none; letter-spacing: 0px; line-height: 1.9em; text-indent: 0.01px; box-sizing: border-box; background-color: rgba(0, 0, 0, 0);">。</span></span></div></div>
    <div class="hover" style="position: absolute; width: 553px; height: 81px; left: 355px; top: 200px; transform: rotate(0deg); display: block;"><div data-v-7bcfe4de="" class="pc_text" style="padding-left: 2px; text-align: center;"><span style="font-family: 微软雅黑; font-size: 80px; color: rgb(47, 46, 46); font-style: normal; font-weight: 700; text-decoration: none; text-shadow: none; letter-spacing: 0px; line-height: 106px; text-indent: 0.01px; box-sizing: border-box; background-color: rgba(0, 0, 0, 0);"><span style="font-size: 80px;"><span style="font-size: 60px; text-indent: 0.01px; font-family: 微软雅黑; color: rgb(27, 27, 27); font-style: normal; font-weight: 700; text-decoration: none; text-shadow: none; letter-spacing: 0px; line-height: normal; box-sizing: border-box; background-color: rgba(0, 0, 0, 0);" id="" class=""><span style="font-family: 微软雅黑; font-size: 60px; color: rgb(27, 27, 27); background-color: rgba(0, 0, 0, 0); font-style: normal; font-weight: 700; text-decoration: none; text-shadow: none; letter-spacing: 0px; line-height: normal;" id=""><span style="font-family: 微软雅黑; font-size: 60px; color: rgb(27, 27, 27); background-color: rgba(0, 0, 0, 0); font-style: normal; font-weight: 700; text-decoration: none; text-shadow: none; letter-spacing: 0px; line-height: normal;" id="">About us</span></span></span></span></span></div></div>
    </div>
{% endblock %}